import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";



const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Voluteer App",
  description: "Generated by create next app",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  
  return (
    <html lang="en">
      <body className={`${oswald.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
